# Generated by Django 5.1.1 on 2025-08-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('username__iexact', 'me'), _negated=True), name='username_not_me'),
        ),
    ]
