# Generated by Django 5.1.1 on 2025-08-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_username_not_me'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='username_not_me',
        ),
    ]
