# Generated by Django 5.1.1 on 2025-08-27 21:19

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_account_username_not_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.models.validate_username]),
        ),
    ]
