# Generated by Django 5.1.1 on 2025-08-27 21:37

import django.core.validators
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.validate_username, django.core.validators.RegexValidator(message='Имя пользователя может содержать буквы, цифры, и некоторые знаки', regex='^[\\w.@+-]+\\Z')], verbose_name='Имя пользователя'),
        ),
    ]
