# Generated by Django 5.1.1 on 2025-08-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_comment_text_alter_review_text'),
        ('reviews', '0002_initial'),
    ]

    operations = [
    ]
